from queue import LifoQueue
n=int(input("Enter the size of stack:"))
stack=LifoQueue(maxsize=n)
stack.put(1)
stack.put(2)
stack.put(3)
stack.put(4)
print(stack.full())
print(stack.qsize())
print(stack.empty())
print(stack.get())
print(stack.get())
print(stack.get())
print(stack.get())